/* Run: PLAYWRIGHT_MODULE=/path/to/playwright node auditoria/independencia.cjs
   Each app is served as the ONLY HTTP root; internet requests fail the audit. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const repo=path.resolve(__dirname,'..'), apps=['dilema-bonde','dilema-bonde-mobile','casos-eticos'];
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg','.ttf':'font/ttf','.woff2':'font/woff2'};
(async()=>{const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});const report=[];
try{for(const app of apps){const root=path.join(repo,app),missing=[],external=[],errors=[],requested=new Set();
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){missing.push(pathname);res.writeHead(404);return res.end()}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port,context=await browser.newContext({viewport:app.includes('mobile')?{width:844,height:390}:{width:1440,height:900}}),page=await context.newPage();await context.route('**/*',r=>{const u=r.request().url();if(u.startsWith(base+'/')){requested.add(new URL(u).pathname);return r.continue()}if(/^(data:|blob:)/.test(u))return r.continue();external.push(u);return r.abort()});page.on('pageerror',e=>errors.push(e.message));const checks=[];
try{await page.goto(base+'/index.html');await page.evaluate(()=>document.fonts.ready);checks.push('load with local fonts');
if(app!=='casos-eticos'){
 await page.locator('#btnMap').click();await page.locator('#freeModeToggle').click();await page.locator('#scenarioMainSlider').fill('5');await page.locator('#scenarioMainSlider').dispatchEvent('input');await page.locator('#scenarioSideSlider').fill('2');await page.locator('#scenarioSideSlider').dispatchEvent('input');assert.equal(await page.locator('#mainLabel').textContent(),'5');assert.equal(await page.locator('#sideLabel').textContent(),'2');await page.locator('#scenarioOk').click();checks.push('free scenario 5 / 2');
 for(const name of ['Manter o curso','Desviar o bonde']){await page.getByRole('button',{name:'Reiniciar',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await page.waitForTimeout(120);await page.getByRole('button',{name:'Pausar',exact:true}).click();checks.push(name+' + play/pause/reset')}
 await page.locator('#btnVolume').click();await page.locator('#volumeSlider').fill('0');await page.locator('#volumeSlider').dispatchEvent('input');await page.locator('#btnVolume').click();checks.push('volume');
 await page.locator('#btnSettings').click();await page.locator('#loopToggle').click();await page.locator('#settingsOk').click();await page.locator('#timerBtn').click();await page.locator('#timerSlider').fill('3');await page.locator('#timerSlider').dispatchEvent('input');await page.locator('#timerPopoverOk').click();
 for(const name of ['Manter o curso','Desviar o bonde']){await page.getByRole('button',{name:'Reiniciar',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Reproduzir',exact:true}).click();await page.locator('#ethicsOverlay:not(.hidden)').waitFor({timeout:20000});assert((await page.locator('#ethicsList').innerText()).length>30);await page.locator('#ethicsOk').click();checks.push(name+' -> complete outcome and ethical feedback')}

 await page.locator('#btnMap').click();await page.locator('#humorToggle').click();assert.equal(await page.locator('#humorToggle').getAttribute('aria-checked'),'true');await page.locator('#humorToggle').click();await page.locator('#scenarioOk').click();checks.push('humor original');
 assert.equal(await page.locator('#soundHumorToggle').count(),app==='dilema-bonde'?1:0);
 // Check every local asset, including characters/audio not drawn in this sample.
 for(const name of fs.readdirSync(path.join(root,'assets'))){if(fs.statSync(path.join(root,'assets',name)).isFile()){const response=await context.request.get(base+'/assets/'+name);assert.equal(response.status(),200)}}checks.push('all character, SVG and audio assets');
}else{
 const themes=await page.locator('.theme-btn:not([disabled])').count();assert(themes>0);for(const level of ['complete','limited']){await page.goto(base+'/index.html');await page.locator('.theme-btn:not([disabled])').first().click();await page.locator('[data-level="'+level+'"]').click();await page.getByRole('button',{name:'Iniciar investigação',exact:true}).click();const clues=page.locator('.clue:not([aria-disabled="true"])');for(let i=0;i<await clues.count();i++)await clues.nth(i).click();await page.locator('#btnGoDecision').click();if(await page.locator('.decision-card').first().isVisible())await page.locator('.decision-card').first().click();else await page.locator('#btnConfirmConduct').click();await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.locator('#btnConfirmTension').click();await page.locator('#btnVerLeitura').click();assert(await page.locator('#screen-leitura').isVisible());checks.push('investigation '+level+' -> decision -> reflection -> ethical reading')}
 const file=await page.evaluate(()=>{const wb=XLSX.utils.book_new();const sheet=(name,rows)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([[],[],[],...rows]),name);sheet('Casos',[['caso_id','status','categoria','titulo_curto','titulo_entrada'],['audit','publicado','Auditoria','Caso de teste','Caso de teste']]);sheet('Pistas',[['caso_id','pista_id','titulo','texto_revelado'],['audit','p1','Fonte','Informação de teste']]);sheet('Decisoes',[['caso_id','decisao_id','letra','titulo'],['audit','d1','A','Opção de teste']]);return XLSX.write(wb,{bookType:'xlsx',type:'base64'})});await page.locator('#workbookInput').setInputFiles({name:'auditoria.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(file,'base64')});await page.waitForFunction(()=>document.getElementById('workbookStatus').textContent.includes('1 caso carregado com sucesso'));checks.push('local XLSX import (synthetic workbook, browser only)');
}
 assert.deepEqual(missing,[]);assert.deepEqual(external,[]);assert.deepEqual(errors,[]);report.push({app,checks,requests:[...requested].sort(),missing,external,errors});console.log('PASS',app,checks.length,'checks');
}finally{await context.close();await new Promise(r=>server.close(r))}}
console.log(JSON.stringify(report,null,2));if(process.env.AUDIT_OUTPUT)fs.writeFileSync(process.env.AUDIT_OUTPUT,JSON.stringify(report,null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
